In [ ]:
# import pandas
import pandas as pd
# Read the data using csv
data=pd.read_csv('data/employee.csv')
data

            name   age   income gender  department grade  performance_score
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723
1        S Kumar   NaN  16000.0      F     Finance    G0                520
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
5  Satyam Sharma   NaN  62000.0    NaN       Sales    G3                649
6   James Authur  54.0      NaN      F  Operations    G3                 53
7     Josh Wills  54.0  52000.0      F     Finance    G3                901
8       Leo Duck  23.0  98000.0      M       Sales    G4                709

In [ ]:
# Let's take a look at the first 5 records
# with first 7 columns using the iloc[:5,:7] method:
# See initial 3 records
data.iloc[:10,:7]

            name   age   income gender  department grade  performance_score
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723
1        S Kumar   NaN  16000.0      F     Finance    G0                520
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
5  Satyam Sharma   NaN  62000.0    NaN       Sales    G3                649
6   James Authur  54.0      NaN      F  Operations    G3                 53
7     Josh Wills  54.0  52000.0      F     Finance    G3                901
8       Leo Duck  23.0  98000.0      M       Sales    G4                709

In [ ]:
data.tail()

            name   age   income gender  department grade  performance_score
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
5  Satyam Sharma   NaN  62000.0    NaN       Sales    G3                649
6   James Authur  54.0      NaN      F  Operations    G3                 53
7     Josh Wills  54.0  52000.0      F     Finance    G3                901
8       Leo Duck  23.0  98000.0      M       Sales    G4                709

In [ ]:
data.iloc[len(data)-5:len(data)]

            name   age   income gender  department grade  performance_score
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
5  Satyam Sharma   NaN  62000.0    NaN       Sales    G3                649
6   James Authur  54.0      NaN      F  Operations    G3                 53
7     Josh Wills  54.0  52000.0      F     Finance    G3                901
8       Leo Duck  23.0  98000.0      M       Sales    G4                709

In [ ]:
# We can check the list of columns using the columns attribute:
# Print list of columns in the data
print(data.columns)

Index(['name', 'age', 'income', 'gender', 'department', 'grade',
       'performance_score'],
      dtype='object')

In [ ]:
# Let's check out the list of columns by using
# the shape of the DataFrame by using the shape attribute:
# Print the shape of a DataFrame
print(data.shape)

(9, 7)

In [ ]:
# We can check the table schema, its columns, rows, data types,
# and missing values in the DataFrame by using the following code:
# Check the information of DataFrame
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               9 non-null      object
 1   age                7 non-null      float64
 2   income             7 non-null      float64
 3   gender             7 non-null      object
 4   department         9 non-null      object
 5   grade              9 non-null      object
 6   performance_score  9 non-null      int64
dtypes: float64(2), int64(1), object(4)
memory usage: 636.0+ bytes

In [ ]:
# Check the descriptive statistics
data.describe()

             age        income  performance_score
count   7.000000      7.000000           9.000000
mean   40.428571  52857.142857         610.666667
std    12.204605  26028.372797         235.671912
min    23.000000  16000.000000          53.000000
25%    31.000000  38500.000000         556.000000
50%    45.000000  52000.000000         674.000000
75%    49.500000  63500.000000         711.000000
max    54.000000  98000.000000         901.000000